apiVersion: v1
kind: Service
metadata:
  name: {{ template "wasabi.fullname" . }}
  labels:
    app: {{ template "wasabi.name" . }}
    chart: {{ template "wasabi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.wasabi.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "wasabi.name" . }}
    release: {{ .Release.Name }}
